"use client";

import { useState } from "react";
import { Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useExplainPurchaseOrder, useExplainTransfer } from "@/features/assistant/hooks";

/** "Explain this recommendation" — grounds the LLM's answer in the real
 * transfer/purchase-order fields (see AssistantService server-side), never
 * predicts a number itself. Reused on Optimization and Procurement rows. */
export function ExplainButton({ kind, id }: { kind: "transfer" | "purchase-order"; id: string }) {
  const [open, setOpen] = useState(false);
  const explainTransfer = useExplainTransfer();
  const explainOrder = useExplainPurchaseOrder();
  const mutation = kind === "transfer" ? explainTransfer : explainOrder;

  const handleOpen = () => {
    setOpen(true);
    if (!mutation.data) mutation.mutate(id);
  };

  return (
    <>
      <Button variant="ghost" size="sm" onClick={handleOpen}>
        <Sparkles className="h-3.5 w-3.5" /> Explain
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>AI explanation</DialogTitle>
            <DialogDescription>Generated by the Groq-backed assistant — explanation only.</DialogDescription>
          </DialogHeader>
          <p className="text-sm leading-relaxed">
            {mutation.isPending
              ? "Thinking…"
              : mutation.isError
                ? "Couldn't generate an explanation right now."
                : mutation.data?.explanation}
          </p>
        </DialogContent>
      </Dialog>
    </>
  );
}
