import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is regenerated by Next.js itself (its triple-slash
    // reference is the standard/required form) — never hand-edited, never
    // worth linting.
    ignores: ["node_modules/**", ".next/**", "tests/**", "vitest.config.ts", "next-env.d.ts"],
  },
];

export default eslintConfig;
