"""initial schema

Autogenerated from app/infrastructure/db/models.py via `alembic revision
--autogenerate`, then hand-extended with three things Alembic's
table/column diff can't express on its own:

  1. `CREATE EXTENSION timescaledb` — required before hypertables can exist.
  2. `create_hypertable(...)` for the 6 append-only, time-indexed tables
     (see `app.infrastructure.db.models.HYPERTABLES`).
  3. Seeding the 4 default RBAC roles, so a fresh environment can register
     its first user immediately (`AuthService.register` requires the
     target role to already exist — see docs/database.md).

Revision ID: 7a03210376fe
Revises:
Create Date: 2026-08-05 19:48:13.052932
"""
from __future__ import annotations

import os
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a03210376fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Table -> time column for every TimescaleDB hypertable. Kept in sync with
# `app.infrastructure.db.models.HYPERTABLES` by convention (this file must
# stay a standalone historical record and can't import app code that may
# change shape later, so the mapping is duplicated here deliberately).
_HYPERTABLES: dict[str, str] = {
    "inventory_history": "recorded_at",
    "consumption": "consumed_at",
    "weather": "recorded_date",
    "forecasts": "generated_at",
    "expiry_risk": "evaluated_at",
    "audit_logs": "created_at",
}

# Mirrors AuthService.DEFAULT_ROLE ("viewer") and the RBAC roles referenced
# by app/api/v1/deps.py::require_role(...).
_DEFAULT_ROLES: list[tuple[str, list[str]]] = [
    ("admin", ["*"]),
    ("hospital_manager", ["hospitals:write", "transfers:write", "procurement:write"]),
    ("pharmacist", ["medicines:write", "inventory:write"]),
    ("viewer", []),
]


def upgrade() -> None:
    # Managed PostgreSQL products such as Render's free database don't offer
    # TimescaleDB. The schema also works as regular PostgreSQL tables.
    timescaledb_enabled = os.getenv("ENABLE_TIMESCALEDB", "true").lower() in {
        "1", "true", "yes"
    }
    if timescaledb_enabled:
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('bed_capacity', sa.Integer(), nullable=False),
    sa.Column('occupancy_rate', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'SPECIALTY', 'TEACHING', 'CLINIC', name='hospital_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_code'), 'hospitals', ['code'], unique=True)
    op.create_index(op.f('ix_hospitals_region'), 'hospitals', ['region'], unique=False)
    op.create_table('medicines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('atc_code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('requires_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_category'), 'medicines', ['category'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('flu_activity_index', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'recorded_date')
    )
    op.create_index(op.f('ix_weather_recorded_date'), 'weather', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_weather_region'), 'weather', ['region'], unique=False)
    op.create_table('alerts',
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('type', sa.Enum('SHORTAGE_RISK', 'EXPIRY_RISK', 'LOW_STOCK', 'TRANSFER_SUGGESTED', name='alert_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_hospital_id'), 'alerts', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_alerts_medicine_id'), 'alerts', ['medicine_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.Enum('CHRONOS', 'LIGHTGBM', name='forecast_model_type'), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=False),
    sa.Column('confidence_high', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id', 'generated_at')
    )
    op.create_index(op.f('ix_forecasts_generated_at'), 'forecasts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_forecasts_hospital_id'), 'forecasts', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_forecasts_medicine_id'), 'forecasts', ['medicine_id'], unique=False)
    op.create_table('inventory',
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=120), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('manufactured_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('unit_cost_at_receipt', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='One row per physical batch of a medicine at a hospital.'
    )
    op.create_index(op.f('ix_inventory_expiry_date'), 'inventory', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_hospital_id'), 'inventory', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_inventory_medicine_id'), 'inventory', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_inventory_supplier_id'), 'inventory', ['supplier_id'], unique=False)
    op.create_table('patients',
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('anonymized_ref', sa.String(length=64), nullable=False),
    sa.Column('age_band', sa.String(length=20), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('primary_diagnosis_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_anonymized_ref'), 'patients', ['anonymized_ref'], unique=False)
    op.create_index(op.f('ix_patients_hospital_id'), 'patients', ['hospital_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECOMMENDED', 'APPROVED', 'ORDERED', 'RECEIVED', 'CANCELLED', name='purchase_order_status'), nullable=False),
    sa.Column('recommended_by', sa.Enum('AI', 'MANUAL', name='recommended_by'), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_hospital_id'), 'purchase_orders', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_medicine_id'), 'purchase_orders', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('consumption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id', 'consumed_at')
    )
    op.create_index(op.f('ix_consumption_consumed_at'), 'consumption', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_consumption_hospital_id'), 'consumption', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_consumption_medicine_id'), 'consumption', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_consumption_patient_id'), 'consumption', ['patient_id'], unique=False)
    op.create_table('expiry_risk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('probability_expires_before_use', sa.Float(), nullable=False),
    sa.Column('estimated_financial_loss', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'evaluated_at')
    )
    op.create_index(op.f('ix_expiry_risk_evaluated_at'), 'expiry_risk', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_expiry_risk_inventory_id'), 'expiry_risk', ['inventory_id'], unique=False)
    op.create_table('inventory_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('RECEIPT', 'CONSUMPTION', 'TRANSFER_OUT', 'TRANSFER_IN', 'EXPIRY_WRITEOFF', 'ADJUSTMENT', name='inventory_change_reason'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    op.create_index(op.f('ix_inventory_history_hospital_id'), 'inventory_history', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_inventory_id'), 'inventory_history', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_medicine_id'), 'inventory_history', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_recorded_at'), 'inventory_history', ['recorded_at'], unique=False)
    op.create_table('transfers',
    sa.Column('source_hospital_id', sa.Uuid(), nullable=False),
    sa.Column('destination_hospital_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='transfer_status'), nullable=False),
    sa.Column('transportation_cost', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('expiry_prevented_value', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['source_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_created_by'), 'transfers', ['created_by'], unique=False)
    op.create_index(op.f('ix_transfers_destination_hospital_id'), 'transfers', ['destination_hospital_id'], unique=False)
    op.create_index(op.f('ix_transfers_medicine_id'), 'transfers', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_transfers_source_hospital_id'), 'transfers', ['source_hospital_id'], unique=False)
    # ### end Alembic commands ###

    # --- Convert append-only time-series tables into TimescaleDB hypertables ---
    if timescaledb_enabled:
        for table_name, time_column in _HYPERTABLES.items():
            op.execute(
                f"SELECT create_hypertable('{table_name}', '{time_column}', "
                f"if_not_exists => TRUE, migrate_data => TRUE)"
            )

    # --- Seed the default RBAC roles ---
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("permissions", sa.JSON()),
    )
    op.bulk_insert(
        roles_table,
        [
            {"id": uuid.uuid4(), "name": name, "permissions": permissions}
            for name, permissions in _DEFAULT_ROLES
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_source_hospital_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_medicine_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_hospital_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_created_by'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_inventory_history_recorded_at'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_medicine_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_inventory_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_hospital_id'), table_name='inventory_history')
    op.drop_table('inventory_history')
    op.drop_index(op.f('ix_expiry_risk_inventory_id'), table_name='expiry_risk')
    op.drop_index(op.f('ix_expiry_risk_evaluated_at'), table_name='expiry_risk')
    op.drop_table('expiry_risk')
    op.drop_index(op.f('ix_consumption_patient_id'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_medicine_id'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_hospital_id'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_consumed_at'), table_name='consumption')
    op.drop_table('consumption')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_medicine_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_hospital_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_patients_hospital_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_anonymized_ref'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_inventory_supplier_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_medicine_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_hospital_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_expiry_date'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_forecasts_medicine_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_hospital_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_generated_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_alerts_medicine_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_hospital_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_weather_region'), table_name='weather')
    op.drop_index(op.f('ix_weather_recorded_date'), table_name='weather')
    op.drop_table('weather')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_category'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_hospitals_region'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_code'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
