"""transfers recommended_by

Milestone C: Optimization proposes transfers via the same
TransferService.propose() every manual proposal goes through, tagged
recommended_by=AI — reuses the `recommended_by` enum type purchase_orders
already defined (see 0001_initial_schema.py), no duplicate enum needed.

server_default is set explicitly (not just the ORM-side Python default)
so this stays correct even against a table that already has rows.

Revision ID: acaf3ef4a22d
Revises: 7a03210376fe
Create Date: 2026-08-06 09:14:12.042831
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaf3ef4a22d'
down_revision: Union[str, None] = '7a03210376fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'transfers',
        sa.Column(
            'recommended_by',
            sa.Enum('AI', 'MANUAL', name='recommended_by'),
            nullable=False,
            server_default='MANUAL',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'recommended_by')
    # ### end Alembic commands ###
